services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "nestjs-app-${DB_NAME}"
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.production
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
  mongo:
    container_name: "mongo-${DB_NAME}"
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: "nest-${DB_NAME}"
    volumes:
      - ./mongo:/data/db
    networks:
      - app-network
  redis:
    container_name: "redis-${DB_NAME}"
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
    app-network: