version: '3'
services:
  db:
    container_name: "mongo-${DB_NAME}"
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: "nest-${DB_NAME}"
    volumes:
      - ./mongo:/data/db


