// Array de nombres de sets de Magic: The Gathering obtenidos de la API de Scryfall
// Actualizado el 26 de junio de 2025

export const scryfallSets: string[] = [
  'Avatar: The Last Airbender',
  "Marvel's Spider-Man Tokens",
  'Final Fantasy Promos',
  'Final Fantasy Tokens',
  'Final Fantasy Commander Tokens',
  'Final Fantasy',
  'Final Fantasy Commander',
  'Aetherdrift',
  'Aetherdrift Tokens',
  'Regional Championship Qualifiers 2025',
  'Pioneer Anthology 1',
  'Alchemy: Tarkir',
  'Tarkir: Dragonstorm Commander',
  'Love Your LGS 2025',
  'Alchemy: Aetherdrift',
  'Aetherdrift Promos',
  'Aetherdrift Commander',
  'Year of the Snake 2025',
  'Aetherdrift Commander Tokens',
  'Japan Standard Cup',
  'MagicFest 2025',
  'Innistrad Remastered Art Series',
  'Innistrad Remastered',
  'Innistrad Remastered Tokens',
  'Wizards Play Network 2025',
  'Pioneer Masters',
  'Mystery Booster 2 Convention Edition 2025',
  'Foundations',
  'Foundations Tokens',
  'Foundations Jumpstart Front Cards',
  'Foundations Jumpstart',
  'Foundations Front Cards',
  'Foundations Commander',
  'Foundations Commander Tokens',
  'Tales of Middle-earth Deluxe Commander Kit',
  'Duskmourn: House of Horror',
  'Duskmourn Tokens',
  'Duskmourn Commander Tokens',
  'Duskmourn Commander',
  'Duskmourn: House of Horror Promos',
  'Duskmourn: House of Horror Art Series',
  'Bloomburrow',
  'Bloomburrow Promos',
  'Bloomburrow Tokens',
  'Bloomburrow Commander',
  'Bloomburrow Commander Tokens',
  'Cowboy Bebop',
  "Assassin's Creed",
  "Assassin's Creed Art Series",
  "Assassin's Creed Tokens",
  'Modern Horizons 3',
  'Modern Horizons 3 Commander',
  'Mystery Booster 2',
  'Bloomburrow',
  'Modern Horizons 3 Tokens',
  'Modern Horizons 3 Commander Tokens',
  'Modern Horizons 2 Timeshifts',
  'Outlaws of Thunder Junction',
  'Outlaws of Thunder Junction Commander',
  'Outlaws of Thunder Junction: The Big Score',
  'The Big Score Tokens',
  'Outlaws of Thunder Junction Art Series',
  'Outlaws of Thunder Junction Tokens',
  'Outlaws of Thunder Junction Commander Tokens',
  'Outlaws of Thunder Junction Promos',
  'Fallout',
  'Fallout Tokens',
  'Murders at Karlov Manor',
  'Alchemy: Murders at Karlov Manor',
  'Ravnica: Clue Edition',
  'Murders at Karlov Manor Art Series',
  'Murders at Karlov Manor Commander',
  'Murders at Karlov Manor Tokens',
  'Murders at Karlov Manor Promos',
  'Special Guests',
  'Ravnica Remastered',
  'Ravnica Remastered Tokens',
  'The Lost Caverns of Ixalan',
  'The Lost Caverns of Ixalan Commander',
  'The Lost Caverns of Ixalan Art Series',
  'The Lost Caverns of Ixalan Tokens',
  'The Lost Caverns of Ixalan Promos',
  'Doctor Who',
  'Doctor Who Tokens',
  'Ixalan',
  'The Lost Caverns of Ixalan Commander Tokens',
  'Jurassic World Collection',
  'Wilds of Eldraine',
  'Wilds of Eldraine Commander',
  'Wilds of Eldraine: Enchanting Tales',
  'Wilds of Eldraine Tokens',
  'Wilds of Eldraine Commander Tokens',
  'Wilds of Eldraine Art Series',
  'Wilds of Eldraine Promos',
  'Commander Masters',
  'Commander Masters Tokens',
  '2022 Heroes of the Realm',
  'Historic Anthology 7',
  'The Lord of the Rings: Tales of Middle-earth',
  'Tales of Middle-earth Promos',
  'Tales of Middle-earth Commander',
  'Tales of Middle-earth Tokens',
  'Tales of Middle-earth Commander Tokens',
  'Tales of Middle-earth Art Series',
  'Tales of Middle-earth Front Cards',
  'The Lord of the Rings: Tales of Middle-earth',
  'March of the Machine',
  'March of the Machine: The Aftermath',
  'March of the Machine Commander',
  'March of the Machine Art Series',
  'March of the Machine Tokens',
  'March of the Machine Commander Tokens',
  'March of the Machine Promos',
  'Shadows of the Past',
  'Multiverse Legends',
  'Phyrexia: All Will Be One',
  'Phyrexia: All Will Be One Commander',
  'Unknown Event',
  'Year of the Rabbit 2023',
  'Phyrexia: All Will Be One Promos',
  'Phyrexia: All Will Be One Art Series',
  'Phyrexia: All Will Be One Tokens',
  'Phyrexia: All Will Be One Minigames',
  'Phyrexia: All Will Be One Commander',
  'Phyrexia: All Will Be One Commander Tokens',
  "The Brothers' War",
  "The Brothers' War Commander",
  "The Brothers' War Retro Artifacts",
  "The Brothers' War Art Series",
  "The Brothers' War Tokens",
  "The Brothers' War Commander Tokens",
  "The Brothers' War Promos",
  'Transformers',
  'Transformers Tokens',
  'Dominaria Remastered',
  'Dominaria Remastered Tokens',
  'Regional Championship Qualifiers 2023',
  'Judge Gift Cards 2023',
  "Alchemy: The Brothers' War",
  'Explorer Anthology 2',
  'Starter Commander Decks Tokens',
  'Starter Commander Decks',
  'Jumpstart 2022 Front Cards',
  'Jumpstart 2022',
  '30th Anniversary Tokens',
  '30th Anniversary Edition',
  "The Brothers' War Jumpstart Front Cards",
  "The Brothers' War Jumpstart",
  'Secret Lair Commander Deck',
  'Game Night: Free-for-All',
  'Game Night: Free-for-All Tokens',
  'Unfinity',
  'Unfinity Sticker Sheets',
  'Unfinity Tokens',
  'Warhammer 40,000 Commander',
  'Warhammer 40,000 Commander Tokens',
  'Alchemy: Dominaria',
  'Regional Championship Qualifiers 2022',
  '30th Anniversary History Promos',
  '30th Anniversary Play Promos',
  '30th Anniversary Misc Promos',
  'Dominaria United',
  'Dominaria United Jumpstart Front Cards',
  'Dominaria United Commander',
  'Dominaria United Tokens',
  'Dominaria United Commander Tokens',
  'Dominaria United Promos',
  '2021 Heroes of the Realm',
  'Historic Anthology 6',
  'Double Masters 2022',
  'Double Masters 2022 Tokens',
  "Alchemy: Baldur's Gate",
  'Historic Brawl',
  'Love Your LGS 2022',
  "Battle for Baldur's Gate Promos",
  "Commander Legends: Battle for Baldur's Gate",
  "Battle for Baldur's Gate Art Series",
  "Battle for Baldur's Gate Tokens",
  'Streets of New Capenna',
  'Streets of New Capenna Southeast Asia Tokens',
  'New Capenna Commander',
  'Streets of New Capenna Tokens',
  'New Capenna Commander Tokens',
  'Streets of New Capenna Promos',
  'New Capenna Art Series',
  'Kamigawa: Neon Dynasty',
  'Year of the Tiger 2022',
  'Kamigawa: Neon Dynasty Promos',
  'Neon Dynasty Commander',
  'Neon Dynasty Art Series',
  'Neon Dynasty Commander Tokens',
  'Kamigawa: Neon Dynasty Tokens',
  'Kamigawa: Neon Dynasty',
  'Innistrad: Double Feature',
  'Judge Gift Cards 2022',
  'Alchemy: Innistrad',
  'Innistrad: Crimson Vow Promos',
  'Crimson Vow Commander Display Commanders',
  'Innistrad: Crimson Vow',
  'Innistrad: Crimson Vow Tokens',
  'Crimson Vow Commander Tokens',
  'Innistrad: Crimson Vow Minigames',
  'Crimson Vow Art Series',
  'Crimson Vow Commander',
  'Innistrad: Crimson Vow',
  'Innistrad: Midnight Hunt',
  'Midnight Hunt Commander',
  'Midnight Hunt Art Series',
  'Innistrad: Midnight Hunt Substitute Cards',
  'Innistrad: Midnight Hunt Tokens',
  'Midnight Hunt Commander Tokens',
  'Innistrad: Midnight Hunt Promos',
  'Innistrad: Midnight Hunt',
  'Jumpstart: Historic Horizons',
  'Adventures in the Forgotten Realms',
  'Forgotten Realms Commander Display Commanders',
  'Adventures in the Forgotten Realms Art Series',
  'Adventures in the Forgotten Realms Tokens',
  'Forgotten Realms Commander',
  'Forgotten Realms Commander Tokens',
  'Adventures in the Forgotten Realms',
  'Adventures in the Forgotten Realms Promos',
  'Love Your LGS 2021',
  'Modern Horizons 1 Timeshifts',
  'Modern Horizons 2',
  'Historic Anthology 5',
  'Strixhaven: School of Mages',
  'Strixhaven Commander',
  'Strixhaven: School of Mages Tokens',
  'Strixhaven: School of Mages Substitute Cards',
  'Strixhaven Mystical Archive',
  'Strixhaven: School of Mages',
  'Commander 2021 Display Commanders',
  'Commander 2021',
  'Commander 2021 Tokens',
  'Time Spiral Remastered',
  'Time Spiral Remastered Tokens',
  'Historic Anthology 4',
  'Kaldheim',
  'Kaldheim Substitute Cards',
  'Kaldheim Art Series',
  'Kaldheim Tokens',
  'Kaldheim',
  'Kaldheim Commander',
  'Kaldheim Commander Tokens',
  'Judge Gift Cards 2021',
  'Commander Legends',
  'Commander Legends Promos',
  'Commander Legends Tokens',
  'Kaladesh Remastered',
  'The List',
  'Zendikar Rising Promos',
  'Zendikar Rising Commander Tokens',
  'Zendikar Rising Tokens',
  'Zendikar Rising Art Series',
  'Zendikar Expeditions',
  'Zendikar Rising',
  'Zendikar Rising Minigames',
  'Zendikar Rising Substitute Cards',
  'Zendikar Rising Commander',
  'Amonkhet Remastered',
  'Arena Beginner Set',
  'Jumpstart Arena Exclusives',
  'Double Masters',
  'Jumpstart',
  'Double Masters Tokens',
  '2019 Heroes of the Realm',
  'Historic Anthology 3',
  'Core Set 2021',
  'Core Set 2021 Promos',
  'Core Set 2021 Tokens',
  'Core Set 2021',
  'Love Your LGS 2020',
  'Ikoria: Lair of Behemoths',
  'Ikoria: Lair of Behemoths Promos',
  'Ikoria: Lair of Behemoths Art Series',
  'Ikoria: Lair of Behemoths Tokens',
  'Ikoria Lair of Behemoths Tokens',
  'Commander 2020 Display Commanders',
  'Commander 2020',
  'Commander 2020 Tokens',
  'Theros Beyond Death',
  'Theros Beyond Death Commander',
  'Theros Beyond Death Art Series',
  'Theros Beyond Death Tokens',
  'Theros Beyond Death Commander Tokens',
  'Historic Anthology 2',
  'Unsanctioned',
  'Theros Beyond Death Promos',
  'Theros Beyond Death Tokens',
  'Judge Gift Cards 2020',
  'Historic Anthology 1',
  'Secret Lair Drop',
  'Game Night 2019 Tokens',
  'Game Night 2019',
  'Throne of Eldraine',
  'Throne of Eldraine Promos',
  'Throne of Eldraine Art Series',
  'Throne of Eldraine Tokens',
  'Commander 2019 Oversized',
  'Commander 2019',
  'Commander 2019 Tokens',
  '2018 Heroes of the Realm',
  'Core Set 2020 Promos',
  'Core Set 2020',
  'Core Set 2020 Tokens',
  'Modern Horizons',
  'Modern Horizons Tokens',
  'War of the Spark',
  'War of the Spark Art Series',
  'War of the Spark Tokens',
  'War of the Spark Promos',
  'Judge Gift Cards 2019',
  'RNA Ravnica Weekend',
  'RNA Guild Kit Tokens',
  'RNA Guild Kit',
  'Ravnica Allegiance Promos',
  'Ravnica Allegiance',
  'Ravnica Allegiance Tokens',
  'Ultimate Masters',
  'Ultimate Masters Tokens',
  'GRN Ravnica Weekend',
  'GRN Guild Kit Tokens',
  'GRN Guild Kit',
  'Guilds of Ravnica',
  'Guilds of Ravnica Promos',
  'Guilds of Ravnica Art Series',
  'Guilds of Ravnica Tokens',
  'Mythic Edition',
  'Commander 2018 Oversized',
  'Commander 2018',
  'Commander 2018 Tokens',
  '2017 Heroes of the Realm',
  'Arena New Player Experience Extras',
  'Arena New Player Experience',
  'Arena New Player Experience Cards',
  'Core Set 2019 Promos',
  'Core Set 2019',
  'Core Set 2019 Tokens',
  'Spellbook: Jace',
  'Battlebond Promos',
  'Battlebond Tokens',
  'Battlebond',
  'Commander Anthology Volume II',
  'Dominaria',
  'Dominaria Promos',
  'Dominaria Art Series',
  'Dominaria Tokens',
  'Masters 25',
  'Masters 25 Tokens',
  'Rivals of Ixalan',
  'Rivals of Ixalan Promos',
  'Rivals of Ixalan Art Series',
  'Rivals of Ixalan Tokens',
  'Nationals Promos',
  'Rivals of Ixalan',
  'Judge Gift Cards 2018',
  'Friday Night Magic 2018',
  'Unstable Promos',
  'Unstable Tokens',
  'Unstable',
  'Iconic Masters Tokens',
  'Explorers of Ixalan',
  'From the Vault: Transform',
  'XLN Treasure Chest',
  'Iconic Masters',
  'Duel Decks: Merfolk vs. Goblins',
  'Duel Decks: Merfolk vs. Goblins Tokens',
  '2017 Gift Pack',
  'Ixalan Promos',
  'Ixalan',
  'Ixalan Tokens',
  'XLN Standard Showdown',
  'HasCon 2017',
  'Archenemy: Nicol Bolas Tokens',
  'Archenemy: Nicol Bolas',
  'Commander 2017 Oversized',
  'Commander 2017',
  'Commander 2017 Tokens',
  'Hour of Devastation',
  'Hour of Devastation Promos',
  'Hour of Devastation Art Series',
  'Hour of Devastation Tokens',
  'Archenemy: Nicol Bolas Schemes',
  'Commander Anthology',
  'Commander Anthology Tokens',
  'Amonkhet',
  'Amonkhet Tokens',
  'Amonkhet Invocations',
  'Amonkhet',
  'Amonkhet Promos',
  'Welcome Deck 2017',
  'Aether Revolt',
  'Aether Revolt Promos',
  'Aether Revolt Art Series',
  'Aether Revolt Tokens',
  'Aether Revolt',
  'Friday Night Magic 2017',
  'Judge Gift Cards 2017',
  'Treasure Chest',
  'Commander 2016 Oversized',
  'Commander 2016',
  'Commander 2016 Tokens',
  'Kaladesh',
  'Kaladesh Tokens',
  'Kaladesh Inventions',
  'Kaladesh Promos',
  'From the Vault: Lore',
  'Eldritch Moon',
  'Eldritch Moon Promos',
  'Eldritch Moon Art Series',
  'Eldritch Moon Tokens',
  'Eternal Masters Tokens',
  'Eternal Masters',
  'Shadows over Innistrad',
  'Shadows over Innistrad Promos',
  'Shadows over Innistrad Art Series',
  'Shadows over Innistrad Tokens',
  'Welcome Deck 2016',
  'Oath of the Gatewatch',
  'Oath of the Gatewatch Promos',
  'League Tokens 2016',
  'Judge Gift Cards 2016',
  'Friday Night Magic 2016',
  'Commander 2015 Oversized',
  'Commander 2015 Tokens',
  'Commander 2015',
  'BFZ Standard Series',
  'Battle for Zendikar',
  'Battle for Zendikar Promos',
  'Battle for Zendikar Tokens',
  'Zendikar Expeditions',
  'From the Vault: Angels',
  'San Diego Comic-Con 2015',
  'Magic Origins',
  'Magic Origins Promos',
  'Magic Origins Art Series',
  'Magic Origins Tokens',
  'Modern Masters 2015',
  'Modern Masters 2015 Tokens',
  'Tempest Remastered',
  'Tarkir Dragonfury',
  'Dragons of Tarkir Promos',
  'Dragons of Tarkir',
  'Dragons of Tarkir Tokens',
  'Fate Reforged',
  'Fate Reforged Tokens',
  "Ugin's Fate",
  'League Tokens 2015',
  'Friday Night Magic 2015',
  'Judge Gift Cards 2015',
  'Commander 2014',
  'Commander 2014 Tokens',
  'Khans of Tarkir',
  'Khans of Tarkir Promos',
  'Khans of Tarkir Art Series',
  'Khans of Tarkir Tokens',
  'From the Vault: Annihilation',
  'Magic 2015',
  'Magic 2015 Tokens',
  'Magic 2015 Promos',
  'Conspiracy',
  'Conspiracy Tokens',
  'Vintage Masters',
  'Journey into Nyx',
  "Journey into Nyx Hero's Path",
  'Journey into Nyx Tokens',
  'Journey into Nyx Promos',
  'Duel Decks: Jace vs. Vraska',
  'Duel Decks: Jace vs. Vraska Tokens',
  'Battle the Horde',
  'Born of the Gods',
  "Born of the Gods Hero's Path",
  'Born of the Gods Tokens',
  'Born of the Gods Promos',
  'League Tokens 2014',
  'Friday Night Magic 2014',
  'Judge Gift Cards 2014',
  'Commander 2013',
  'Commander 2013 Oversized',
  'Commander 2013 Tokens',
  'Face the Hydra',
  'Theros',
  'Theros Promos',
  'Theros Art Series',
  'Theros Tokens',
  'Duel Decks: Heroes vs. Monsters Tokens',
  'Duel Decks: Heroes vs. Monsters',
  'From the Vault: Twenty',
  'Magic 2014',
  'Magic 2014 Tokens',
  'Magic 2014 Promos',
  "Dragon's Maze",
  "Dragon's Maze Tokens",
  "Dragon's Maze Promos",
  'World Magic Cup Qualifiers',
  'Judge Gift Cards 2013',
  'Friday Night Magic 2013',
  'Gatecrash',
  'Gatecrash Promos',
  'Gatecrash Art Series',
  'Gatecrash Tokens',
  'Duel Decks: Izzet vs. Golgari Tokens',
  'Duel Decks: Izzet vs. Golgari',
  'From the Vault: Realms',
  'Magic 2013',
  'Magic 2013 Promos',
  'Magic 2013 Tokens',
  'Planechase 2012',
  'Planechase 2012 Oversized',
  'Planechase 2012 Tokens',
  'Avacyn Restored',
  'Avacyn Restored Tokens',
  'Open the Helvault',
  'Avacyn Restored Promos',
  'Dark Ascension',
  'Dark Ascension Tokens',
  'Dark Ascension Promos',
  'Wizards Play Network 2012',
  'League Tokens 2012',
  'Friday Night Magic 2012',
  'Judge Gift Cards 2012',
  'Premium Deck Series: Graveborn',
  'Innistrad',
  'Innistrad Tokens',
  'Innistrad Promos',
  'Duel Decks: Ajani vs. Nicol Bolas Tokens',
  'Duel Decks: Ajani vs. Nicol Bolas',
  'From the Vault: Legends',
  'Magic 2012 Tokens',
  'Magic 2012',
  'Magic 2012 Promos',
  'Commander 2011 Oversized',
  'Commander 2011 Launch Party',
  'Commander',
  'Commander Tokens',
  'Duel Decks: Ajani vs. Nicol Bolas',
  'New Phyrexia',
  'New Phyrexia Tokens',
  'New Phyrexia Promos',
  'Duel Decks: Knights vs. Dragons Tokens',
  'Duel Decks: Knights vs. Dragons',
  'Magic Premiere Shop 2011',
  'Duels of the Planeswalkers 2012 Promos',
  'Salvat 2011',
  'Magic Player Rewards 2011',
  'Judge Gift Cards 2011',
  'Friday Night Magic 2011',
  'Mirrodin Besieged',
  'Mirrodin Besieged Promos',
  'Mirrodin Besieged Art Series',
  'Mirrodin Besieged Tokens',
  'From the Vault: Relics',
  'Magic 2011',
  'Magic 2011 Tokens',
  'Magic 2011 Promos',
  'Scars of Mirrodin',
  'Scars of Mirrodin Promos',
  'Scars of Mirrodin Art Series',
  'Scars of Mirrodin Tokens',
  'Duel Decks: Elspeth vs. Tezzeret',
  'Duel Decks: Elspeth vs. Tezzeret Tokens',
  'Worldwake',
  'Worldwake Promos',
  'Worldwake Tokens',
  'Magic Player Rewards 2010',
  'Judge Gift Cards 2010',
  'Friday Night Magic 2010',
  'Zendikar',
  'Zendikar Promos',
  'Zendikar Tokens',
  'Premium Deck Series: Slivers',
  'Duel Decks: Garruk vs. Liliana Tokens',
  'Duel Decks: Garruk vs. Liliana',
  'Zendikar Promos',
  'From the Vault: Exiled',
  'Magic 2010',
  'Magic 2010 Promos',
  'Magic 2010 Tokens',
  'Alara Reborn',
  'Alara Reborn Tokens',
  'Alara Reborn',
  'Alara Reborn Promos',
  'Duel Decks: Divine vs. Demonic',
  'Conflux Promos',
  'Conflux',
  'Conflux Tokens',
  'Magic Player Rewards 2009',
  'Judge Gift Cards 2009',
  'Friday Night Magic 2009',
  'Shards of Alara',
  'Shards of Alara Tokens',
  'Shards of Alara',
  'Shards of Alara Promos',
  'Masters Edition II',
  'From the Vault: Dragons',
  'Eventide Promos',
  'Eventide',
  'Eventide Tokens',
  'Shadowmoor Promos',
  'Shadowmoor',
  'Shadowmoor Tokens',
  '15th Anniversary Cards',
  'Magic Premiere Shop 2008',
  'Friday Night Magic 2008',
  'Judge Gift Cards 2008',
  'Magic Player Rewards 2008',
  'Lorwyn',
  'Lorwyn Promos',
  'Lorwyn Tokens',
  'Masters Edition',
  'Tenth Edition',
  'Tenth Edition Promos',
  'Future Sight',
  'Future Sight Promos',
  'Future Sight Tokens',
  'Magic Player Rewards 2007',
  'Judge Gift Cards 2007',
  'Magic Premiere Shop 2007',
  'Friday Night Magic 2007',
  'Planar Chaos',
  'Planar Chaos Promos',
  'Planar Chaos Tokens',
  'Coldsnap Theme Decks',
  'Coldsnap',
  'Coldsnap Promos',
  'Coldsnap Tokens',
  'Dissension',
  'Dissension Promos',
  'Dissension Tokens',
  'Guildpact',
  'Guildpact Promos',
  'Guildpact Tokens',
  'Magic Premiere Shop 2006',
  'Arena League 2006',
  'Junior APAC Series',
  'Judge Gift Cards 2006',
  'Magic Player Rewards 2006',
  'Friday Night Magic 2006',
  'Two-Headed Giant Tournament',
  'Ravnica: City of Guilds',
  'Ravnica: City of Guilds Promos',
  'Ravnica: City of Guilds Tokens',
  'Salvat 2005',
  'Ninth Edition',
  'Ninth Edition Promos',
  'Betrayers of Kamigawa',
  'Betrayers of Kamigawa Promos',
  'Betrayers of Kamigawa Tokens',
  'Arena League 2005',
  'Junior Series Europe',
  'Magic Player Rewards 2005',
  'Judge Gift Cards 2005',
  'Friday Night Magic 2005',
  'Unhinged',
  'Darksteel',
  'Darksteel Promos',
  'Darksteel Tokens',
  'Arena League 2004',
  'Magic Player Rewards 2004',
  'Friday Night Magic 2004',
  'Judge Gift Cards 2004',
  'Mirrodin',
  'Mirrodin Promos',
  'Mirrodin Tokens',
  'Eighth Edition',
  'Eighth Edition Promos',
  'Scourge',
  'Scourge Promos',
  'Scourge Tokens',
  'Arena League 2003',
  'Vintage Championship',
  'Friday Night Magic 2003',
  'Magic Player Rewards 2003',
  'Legions',
  'Legions Promos',
  'Legions Tokens',
  'Onslaught',
  'Onslaught Promos',
  'Onslaught Tokens',
  'Judge Gift Cards 2002',
  'Magic Player Rewards 2002',
  'Friday Night Magic 2002',
  'Torment',
  'Torment Promos',
  'Torment Tokens',
  'Odyssey',
  'Odyssey Promos',
  'Odyssey Tokens',
  'Seventh Edition',
  'Planeshift Promos',
  'Planeshift',
  'Planeshift Tokens',
  'Friday Night Magic 2001',
  'Magic Player Rewards 2001',
  'Invasion Promos',
  'Invasion',
  'Invasion Tokens',
  'Prophecy',
  'Starter 2000',
  'Nemesis Promos',
  'Nemesis',
  'Nemesis Tokens',
  'European Land Program',
  'Friday Night Magic 2000',
  'Junior Super Series',
  'Masques',
  'Battle Royale Box Set',
  'Mercadian Masques',
  'Mercadian Masques Promos',
  'Mercadian Masques Tokens',
  'Guru',
  'Starter 1999',
  "Urza's Destiny",
  "Urza's Destiny Promos",
  "Urza's Destiny Tokens",
  'Judge Gift Cards 1999',
  'Anthologies',
  "Urza's Legacy",
  "Urza's Legacy Promos",
  "Urza's Legacy Tokens",
  'Portal Second Age',
  'Unglued',
  'Exodus',
  'Stronghold',
  'Judge Gift Cards 1998',
  'Tempest',
  'Weatherlight',
  'Oversized League Prizes',
  'Mirage Championship',
  'Astral Cards',
  'Fifth Edition',
  'Visions',
  'Introductory Two-Player Set',
  'Mirage',
  'Multiverse Gift Box',
  'Arena League 1996',
  'Rivals Quick Start Set',
  "League '96",
  'Alliances',
  'Pro Tour Collector Set',
  'Homelands',
  'Renaissance',
  'Rinascimento',
  'Chronicles',
  'Chronicles Foreign Black Border',
  'Ice Age',
  'Fourth Edition Foreign Black Border',
  'Fourth Edition',
  'Media and Collaboration Promos',
  'The Dark',
  'Fallen Empires',
  'HarperPrism Book Promos',
  'Legends',
  'Antiquities',
  "Intl. Collectors' Edition",
  "Collectors' Edition",
  'Arabian Nights',
  'Unlimited Edition',
  'Limited Edition Beta',
  'Limited Edition Alpha',
];

// Array de tipos de sets de Magic: The Gathering obtenidos de la API de Scryfall
// Actualizado el 26 de junio de 2025
export const scryfallSetTypes: string[] = [
  "token",
  "expansion",
  "promo",
  "memorabilia",
  "commander",
  "alchemy",
  "masters",
  "draft_innovation",
  "core",
  "masterpiece",
  "box",
  "spellbook",
  "duel_deck",
  "from_the_vault",
  "funny",
  "minigame",
  "starter",
  "planechase",
  "treasure_chest",
];

// Función para obtener un set por nombre
export const getScryfallSetByName = (name: string): string | undefined => {
  return scryfallSets.find((set) => set.toLowerCase() === name.toLowerCase());
};

// Función para obtener sets que contengan un término de búsqueda
export const searchScryfallSets = (searchTerm: string): string[] => {
  return scryfallSets.filter((set) =>
    set.toLowerCase().includes(searchTerm.toLowerCase()),
  );
};

// Función para obtener un tipo de set por nombre exacto
export const getScryfallSetTypeByName = (
  typeName: string,
): string | undefined => {
  return scryfallSetTypes.find(
    (type) => type.toLowerCase() === typeName.toLowerCase(),
  );
};

// Función para obtener tipos de sets que contengan un término de búsqueda
export const searchScryfallSetTypes = (searchTerm: string): string[] => {
  return scryfallSetTypes.filter((type) =>
    type.toLowerCase().includes(searchTerm.toLowerCase()),
  );
};

// Función para validar si un tipo de set es válido
export const isValidSetType = (setType: string): boolean => {
  return scryfallSetTypes.some(
    (type) => type.toLowerCase() === setType.toLowerCase(),
  );
};

// Total de sets disponibles
export const TOTAL_SCRYFALL_SETS = scryfallSets.length;

// Total de tipos de sets disponibles
export const TOTAL_SCRYFALL_SET_TYPES = scryfallSetTypes.length;
