services:
  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    container_name: "nestjs-app-${DB_NAME}"
    restart: always
    ports:
      - "${PORT}:8000"
    env_file:
      - .env.production
    environment:
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
      - CACHE_PORT=${CACHE_PORT}
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./logs:/usr/src/app/logs
  redis:
    container_name: "redis-${DB_NAME}"
    image: redis:7
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - CACHE_PORT=${CACHE_PORT}
    networks:
      - app-network
networks:
    app-network:
      driver: bridge