export const EnvConfiguration = () => ({
  environment: process.env.NODE_ENV || 'dev',
  port: +process.env.PORT || 8000,
  app_name: process.env.APP_NAME || 'NestJS API',
  jwt_secret: process.env.JWT_SECRET,
  url_app: process.env.URL_APP || 'http://localhost:8000',
  hash: process.env.HASH,
  db_name: process.env.DB_NAME,
  db_uri: process.env.DB_URI,
  cache_host: process.env.CACHE_HOST || 'localhost',
  cache_port: +process.env.CACHE_PORT || 6379,
  cache_url: process.env.CACHE_URL || 'redis://localhost:6379',
  url_fullerton: process.env.URL_FULLERTON,
  client_id_fullerton: process.env.CLIENT_ID_FULLERTON,
  secret_key_fullerton: process.env.SECRET_KEY_FULLERTON,
  JWT_HOURS_EXPIRE: +process.env.JWT_HOURS_EXPIRE || 2,
});
