export enum Language {
    JAPANESE = 'ja',
    ENGLISH = 'en',
    SPANISH = 'es',
    FRENCH = 'fr',
    GERMAN = 'de',
    ITALIAN = 'it',
    PORTUGUESE = 'pt',
    KOREAN = 'ko',
    RUSSIAN = 'ru',
    CHINESE_SIMPLIFIED = 'zhs',
    CHINESE_TRADITIONAL = 'zht',
    HEBREW = 'he',
    LATIN = 'la',
    ANCIENT_GREEK = 'grc',
    ARABIC = 'ar',
    SANSKRIT = 'sa',
    PHYREXIAN = 'ph',
    QUENYA = 'qya'
}