name: CI-Deploy-Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 📂 Sync files
        run: |
          rsync -avz --delete -e "ssh -p 22022" ./ ftp_user@152.230.104.5:/var/www/fullerton/
        env:
          RSYNC_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: 🐋 Execute Docker commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22022
          script: |
            cd /var/www/fullerton/
            docker-compose build
            docker-compose up -d